# Generated by Django 5.1.7 on 2025-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_tracks"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="courses",
            field=models.ManyToManyField(related_name="tracks", to="courses.course"),
        ),
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
