# Generated by Django 5.1.7 on 2025-03-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="supervisor",
            field=models.ForeignKey(
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_tracks",
                to="accounts.customuser",
            ),
        ),
    ]
