# Generated by Django 5.1.7 on 2025-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_location", "0001_initial"),
        ("tracks", "0002_alter_track_courses_alter_track_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="branches",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="branch_location.branch"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="track_type",
            field=models.CharField(
                choices=[("ICC", "ICC"), ("9MONTH", "9 Months"), ("OTHER", "Other")],
                default="OTHER",
                help_text="Type of the track (e.g., ICC, 9months, etc.)",
                max_length=20,
                verbose_name="Track Type",
            ),
        ),
    ]
