# Generated by Django 5.1.7 on 2025-03-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tracks", "0002_track_supervisor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_tracks",
                to="accounts.customuser",
            ),
        ),
    ]
