# Generated by Django 5.1.7 on 2025-04-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_location", "0001_initial"),
        ("tracks", "0003_track_branches_track_track_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="branches",
        ),
        migrations.AddField(
            model_name="track",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="branch_location.branch",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_type",
            field=models.CharField(
                choices=[("ICC", "ICC"), ("9month", "9 Month")],
                default="ICC",
                max_length=10,
            ),
        ),
    ]
