# Generated by Django 5.1.7 on 2025-04-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0004_alter_track_supervisor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="track",
            table="tracks",
        ),
    ]
