# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0005_alter_track_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={},
        ),
        migrations.AlterModelTable(
            name="track",
            table="Tracks",
        ),
    ]
