# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0006_alter_track_options_alter_track_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="created_at",
        ),
    ]
