# Generated by Django 5.1.7 on 2025-04-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0009_alter_track_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={},
        ),
        migrations.RemoveField(
            model_name="track",
            name="created_at",
        ),
    ]
