# Generated by Django 5.1.7 on 2025-04-02 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0010_alter_track_options_remove_track_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name="track",
            table=None,
        ),
    ]
