# Generated by Django 5.1.7 on 2025-04-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0011_alter_track_options_track_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="track",
            table="tracks",
        ),
    ]
