# Generated by Django 5.1.7 on 2025-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_tracks"),
        ("tracks", "0012_alter_track_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="course_tracks", to="courses.course"
            ),
        ),
    ]
