# Generated by Django 5.1.7 on 2025-04-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_options_student_is_active_and_more"),
    ]

    operations = []
