# Generated by Django 5.1.7 on 2025-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
