# Generated by Django 5.1.7 on 2025-04-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_add_missing_auth_fields"),
    ]

    operations = []
