# Generated by Django 5.1.7 on 2025-03-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="student_account",
        ),
    ]
