# Generated by Django 5.1.7 on 2025-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="verification_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
