# Generated by Django 5.1.7 on 2025-04-03 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_add_missing_auth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
