# Generated by Django 5.1.7 on 2025-04-01 19:20

import apps.student.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_student_is_superuser_student_verification_code_and_more"),
        ("tracks", "0004_alter_track_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="track",
            field=models.ForeignKey(
                blank=True,
                default=apps.student.models.get_default_track,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
            ),
        ),
    ]
