# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_student_track"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="Students",
        ),
    ]
