# Generated by Django 5.1.7 on 2025-04-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_student_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table=None,
        ),
    ]
