# Generated by Django 5.1.7 on 2025-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_student_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
