# Generated by Django 5.1.7 on 2025-04-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_student_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
    ]
