# Generated by Django 5.1.7 on 2025-04-02 02:49

import apps.student.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_remove_student_name"),
        ("tracks", "0013_track_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="track",
            field=models.ForeignKey(
                blank=True,
                default=apps.student.models.get_default_track,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="tracks.track",
            ),
        ),
    ]
