# Generated by Django 5.1.7 on 2025-04-16 23:57

import apps.grades.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0004_assignment_track"),
        ("courses", "0002_initial"),
        ("student", "0001_initial"),
        ("submission", "0001_initial"),
        ("tracks", "0002_alter_track_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("feedback", models.TextField()),
                (
                    "graded_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assignment",
                    models.ForeignKey(
                        default=apps.grades.models.get_default_assignment,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        default=apps.grades.models.get_default_student,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="student.student",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="submission.assignmentsubmission",
                        verbose_name="Submission",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracks.track",
                        verbose_name="Track",
                    ),
                ),
            ],
            options={
                "db_table": "grades",
                "unique_together": {("student", "assignment", "submission")},
            },
        ),
    ]
