# Generated by Django 5.1.7 on 2025-03-30 16:46

import apps.grades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('student', '0005_student_is_superuser_student_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=apps.grades.models.get_default_student, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student'),
        ),
    ]
