# Generated by Django 5.1.7 on 2025-04-08 05:21

import apps.grades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                default=apps.grades.models.get_default_student,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="student.student",
            ),
        ),
    ]
