# Generated by Django 4.2 on 2025-04-03 03:07

import apps.grades.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=apps.grades.models.get_default_student, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student'),
        ),
    ]
