# Generated by Django 5.1.7 on 2025-04-14 11:07

import apps.grades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0001_initial"),
        ("student", "0001_initial"),
        ("submission", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                default=apps.grades.models.get_default_student,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="student.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="submission.assignmentsubmission",
                verbose_name="Submission",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
                verbose_name="Track",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "assignment", "submission")},
        ),
    ]
