# Generated by Django 5.1.7 on 2025-04-01 19:20

import apps.grades.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
        ("student", "0006_student_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                default=apps.grades.models.get_default_student,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="student.student",
            ),
        ),
    ]
