# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_grade_student"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="grade",
            table="Grades",
        ),
    ]
