# Generated by Django 5.1.7 on 2025-04-02 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_alter_grade_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
