# Generated by Django 5.2 on 2025-04-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_grade_track"),
        ("submission", "0004_alter_assignmentsubmission_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="submission.assignmentsubmission",
                verbose_name="Submission",
            ),
        ),
    ]
