# Generated by Django 5.2 on 2025-04-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignmentstudent_track"),
        ("grades", "0004_grade_submission"),
        ("student", "0001_initial"),
        ("submission", "0004_alter_assignmentsubmission_track"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "assignment", "submission")},
        ),
    ]
