# Generated by Django 5.1.7 on 2025-04-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_alter_grade_created_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="grade",
            table="grades",
        ),
    ]
