# Generated by Django 5.1.7 on 2025-04-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the branch location",
                        max_length=100,
                        unique=True,
                        verbose_name="branch name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short unique code for the branch",
                        max_length=10,
                        unique=True,
                        verbose_name="branch code",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Complete physical address of the branch",
                        verbose_name="full address",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="state/province"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "branch_manager"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_branch",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="branch manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
                "ordering": ["name"],
                "permissions": [("can_manage_branches", "Can manage branch locations")],
            },
        ),
    ]
