# Generated by Django 5.1.7 on 2025-04-03 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                related_name="supervised_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supervisors",
            ),
        ),
    ]
