# Generated by Django 5.2 on 2025-04-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch_location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "branch_manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branch",
                to=settings.AUTH_USER_MODEL,
                verbose_name="branch manager",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                related_name="supervised_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supervisors",
            ),
        ),
    ]
