# Generated by Django 5.1.7 on 2025-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_location", "0002_branch_supervisors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.TextField(verbose_name="full address"),
        ),
    ]
