# Generated by Django 5.1.7 on 2025-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateTimeField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("project", "Project"),
                            ("exam", "Exam"),
                        ],
                        default="homework",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "assignments",
                "ordering": ["-created_at"],
            },
        ),
    ]
