# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="assignment",
            table="Assignment",
        ),
    ]
