# Generated by Django 5.1.7 on 2025-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_alter_assignment_options_alter_assignment_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("homework", "Homework"),
                    ("project", "Project"),
                    ("exam", "Exam"),
                ],
                default="homework",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="assignment",
            table="assignment",
        ),
    ]
