# Generated by Django 5.2 on 2025-04-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        ("courses", "0002_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="assignmentstudent",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.assignment"
            ),
        ),
        migrations.AddField(
            model_name="assignmentstudent",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
    ]
