# Generated by Django 5.1.7 on 2025-04-02 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="end_date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[("task", "Task"), ("project", "Project"), ("exam", "Exam")],
                default="homework",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
