# Generated by Django 5.2 on 2025-04-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assignments",
                through="assignments.AssignmentStudent",
                to="student.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentstudent",
            unique_together={("assignment", "student")},
        ),
    ]
