# Generated by Django 5.1.7 on 2025-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignment_assignment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[("task", "Task"), ("project", "Project"), ("exam", "Exam")],
                default="homework",
                max_length=50,
            ),
        ),
    ]
