# Generated by Django 5.1.7 on 2025-04-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_assignment_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="student",
            new_name="assigned_to",
        ),
    ]
