# Generated by Django 5.2 on 2025-04-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentstudent",
            name="track",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
            preserve_default=False,
        ),
    ]
