# Generated by Django 5.1.7 on 2025-04-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0003_assignment_end_date_alter_assignment_assignment_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
