# Generated by Django 5.2 on 2025-04-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_assignmentstudent_track"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentstudent",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
            ),
        ),
    ]
