# Generated by Django 5.1.7 on 2025-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_rename_student_assignment_assigned_to"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="assignment",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assignments", to="student.student"
            ),
        ),
    ]
