# Generated by Django 5.1.7 on 2025-04-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_remove_assignment_assigned_to_assignment_assigned_to"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="assignment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="student.student",
            ),
        ),
    ]
