# Generated by Django 5.2 on 2025-04-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignmentstudent_track"),
        ("submission", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="track",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.assignment",
            ),
        ),
    ]
