# Generated by Django 5.2 on 2025-04-09 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignmentstudent_track"),
        ("submission", "0002_assignmentsubmission_track_and_more"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.assignment"
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
            ),
        ),
    ]
