# Generated by Django 5.2 on 2025-04-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0003_alter_assignmentsubmission_assignment_and_more"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracks.track",
            ),
        ),
    ]
