# Generated by Django 5.2 on 2025-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
    ]
