# Generated by Django 5.2 on 2025-04-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_set', to='tracks.track'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'track')},
        ),
    ]
