# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="Courses",
        ),
    ]
