# Generated by Django 5.1.7 on 2025-04-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="tracks",
        ),
    ]
