# Generated by Django 5.1.7 on 2025-04-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="track",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_set",
                to="tracks.track",
            ),
        ),
    ]
