# Generated by Django 5.2 on 2025-04-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options_alter_course_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="course",
        ),
    ]
