# Generated by Django 5.1.7 on 2025-04-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
    ]
