# Generated by Django 5.2 on 2025-04-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
    ]
