# Generated by Django 5.1.7 on 2025-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_table"),
        ("tracks", "0012_alter_track_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tracks",
            field=models.ManyToManyField(
                blank=True, related_name="course_tracks", to="tracks.track"
            ),
        ),
    ]
