# Generated by Django 5.1.7 on 2025-04-03 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("staff_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffmember",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "staff member",
                "verbose_name_plural": "staff members",
            },
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="email",
            field=models.EmailField(
                help_text="Required. Must be a valid email address.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="staffmember_groups",
                related_query_name="staffmember",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("branch_manager", "Branch Manager"),
                    ("supervisor", "Supervisor"),
                    ("instructor", "Instructor"),
                ],
                default="instructor",
                max_length=20,
                verbose_name="staff role",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="staffmember_permissions",
                related_query_name="staffmember",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
