# Generated by Django 5.1.7 on 2025-04-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "staff_members",
            "0002_alter_staffmember_options_alter_staffmember_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="branch_location",
            field=models.CharField(
                blank=True,
                help_text="The physical branch location this staff member is associated with",
                max_length=100,
                null=True,
                verbose_name="branch location",
            ),
        ),
    ]
