# Generated by Django 5.1.7 on 2025-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0002_alter_staffmember_options_alter_staffmember_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("branch_manager", "Branch Manager"),
                    ("supervisor", "Supervisor"),
                    ("instructor", "Instructor"),
                ],
                default="instructor",
                max_length=20,
            ),
        ),
    ]
