# Generated by Django 5.1.7 on 2025-04-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_location", "0001_initial"),
        ("staff_members", "0003_staffmember_branch_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffmember",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [("can_manage_branches", "Can manage branch locations")],
                "verbose_name": "staff member",
                "verbose_name_plural": "staff members",
            },
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="branch_location",
        ),
        migrations.AddField(
            model_name="staffmember",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_members",
                to="branch_location.branch",
                verbose_name="assigned branch",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="verification status"
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("branch_manager", "Branch Manager"),
                    ("supervisor", "Supervisor"),
                    ("instructor", "Instructor"),
                    ("admin", "System Administrator"),
                ],
                default="instructor",
                max_length=20,
                verbose_name="staff role",
            ),
        ),
    ]
