# Generated by Django 5.1.7 on 2025-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0003_alter_staffmember_password_alter_staffmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
