# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0004_alter_staffmember_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="staffmember",
            table="StaffMember",
        ),
    ]
