# Generated by Django 5.1.7 on 2025-04-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0005_alter_staffmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("branch_manager", "Branch Manager"),
                    ("supervisor", "Supervisor"),
                    ("instructor", "Instructor"),
                    ("admin", "System Administrator"),
                ],
                default="instructor",
                max_length=20,
                verbose_name="staff role",
            ),
        ),
    ]
