# Generated by Django 5.1.7 on 2025-04-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0005_alter_staffmember_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="staffmember",
            table="Staff_Member",
        ),
    ]
