# Generated by Django 5.1.7 on 2025-04-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_members", "0006_alter_staffmember_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="staffmember",
            table="staff_member",
        ),
    ]
